---
sevahn vorperian
quake lab
urine vs plasma differential expression
"Multiomics characterization of cell type repertoires for urine liquid biopsies"
---


```{r}
# renamed 20221201_bioivt_sed_supt

library(edgeR)
library(ggplot2)
library(limma)

```

```{r}
fsave_path = '../../data/diffex/plasma_urine/'
```


```{r}
# read in the object
counts <- read.csv("../../data/20231228_filtered_sed_supt_bioivt.csv",
                   header = TRUE, row.names = 2)

meta <- read.csv("../../data/20231225_bioivt_urine_meta.csv",
                 header = TRUE)

# drop the gene names; Ensembl ID only
gene_names <- counts[,1]
counts <- counts[,2:ncol(counts)]
```

```{r}
dge <- DGEList(counts = counts)

max(dge$samples$lib.size) / min(dge$samples$lib.size)

# appropriate to do voom with quality weights
```

```{r}
# knit sample type and stone to a single factor
biofluid_disease <- paste0(meta$sample_type, "_", meta$stone_normal)
targets <- as.data.frame(biofluid_disease)

targets$biofluid_disease <- factor(targets$biofluid_disease)
targets$sample_id = factor(meta$patient_id)

targets$sex = meta$sex

targets$volume = meta$vol_samps
targets$volume = as.integer(targets$volume)

targets$leuks = meta$leuks

design <- model.matrix(~0 + targets$biofluid_disease + targets$volume + targets$leuks + targets$sex)
```

```{r}
colnames(design)
```


```{r}
colnames(design) <- c("plasma_normal", "sediment_normal", "sediment_stone", "supt_normal",
                      "supt_stone", "volume", 'leuks', 'sex')
```

```{r}
# compute the biological coefficient of variation (BCV); this will be larger
# than what Chen et al. 2016 (F1000 with Smyth) and the original voom paper 
# discuss for human samples (0.4) because of how distinct plasm and
# urine sedimen/supt are.


dge <- calcNormFactors(dge, method = "TMM")
dge <- estimateDisp(dge, design, robust = TRUE)
sqrt(dge$common.dispersion) 
plotBCV(dge)
```


```{r}
tmm_urine <- data.frame(dge$samples)
write.csv(tmm_urine, paste0(fsave_path, 'TEST_20231228_urine_bioIVT_TMM.csv'))
```


```{r}
vwts <- voomWithQualityWeights(counts = dge, #design = design,
                               design = design,
                               normalize.method = "none",
                               method = "genebygene",
                               plot=TRUE) # dge vs logCPM
```


```{r}
# Repeated samples with different uninteresting predictors: This refers to situations where repeated samples do not have the same set of predictors in the design matrix, e.g., because some repeated samples were processed in a different batch. If the repeated samples for each blocking level have the same pattern of values for those predictors (e.g., each blocking level has one repeated sample in each of three batches), summation is still possible. However, in general, this is not the case and then duplicateCorrelation must be used.
# https://support.bioconductor.org/p/125489/


# duplicateCorrelation documentation: "if block is not null, this function estimates the correlation between repeated observations on the blocking variable. typicallly the blocks are biological replicates and repeated observations on the same block may be correlated... the function also returns a consensus correlation, which is a robust average of the individual correlations, intended for input to the functions such as lmFit or voom.."

# For this function to return statistically useful results, there must be at least two more arrays than the number of coefficients to be estimated, i.e., two more than the column rank of design.
# -> need to confirm that this is overall not within a given block (i think
# it's overall)

corfit <- duplicateCorrelation(vwts, design, block = targets$sample_id)
```

```{r}
corfit$consensus
corfit$consensus.correlation
```

```{r}
# run voomWithQualityWeights twice 
# https://support.bioconductor.org/p/59700/
# 
# The voom plot shows how the coefficient of variation of the counts depends on the count size. To understand more, read the article that Benjamin Rodriguez links to. The meaning of the plot was discussed at length in that article.

vwts <- voomWithQualityWeights(counts = dge,
                               design = design,
                               normalize.method = "none",
                               method = "genebygene",
                               block = targets$sample_id,
                               correlation = corfit$consensus,
                               plot=TRUE) # dge vs logCPM
```

```{r}
# copy page 126 of the manual
corAgain <- duplicateCorrelation(vwts, design, block = targets$sample_id) 
```


```{r}
vfit2 <- lmFit(vwts, design,
               block = targets$sample_id,
               correlation = corfit$consensus)
```


```{r}
# page 50

# extract contrasts of interest
cm_plasma_urine <- makeContrasts(
  # compare sediment and supernatant
  plasma_supt_normal = plasma_normal - supt_normal,
  plasma_sediment_normal = plasma_normal - sediment_normal,
  plasma_sediment_all = plasma_normal - (sediment_normal + sediment_stone) / 2,
  plasma_supt_all = plasma_normal - (supt_normal + supt_stone) / 2,
  levels = colnames(design)
)
```




```{r}
# You should not use voom() together with eBayes(trend=TRUE). You should use one or the other, but not both (as explained in Chapter 15 of the limma User's Guide).
# https://support.bioconductor.org/p/98201/

# apply the diff sets of contrast matrices
vfit_urine <- contrasts.fit(vfit2, cm_plasma_urine)

# trend is false since this is voom and it is baked in
vfit_urine <- eBayes(vfit_urine, trend = FALSE, robust = TRUE) 
```


```{r}
# perform decideTests to account for MH testing across the extracted contrasts
# this is essentially a numeric matrix with elements -1, 0 or 1 depending on whether each t-statistic is classified as significantly negative, not significant or significantly positive respectively

urineDecideTests <- decideTests(vfit_urine, method = "global", p.value = 0.05)
print(summary(urineDecideTests))
urineDecideTests <- as.data.frame(urineDecideTests)
```


```{r}

# isolate the DEGs for a given contrast and apply MH 
for (contrast_coef in colnames(vfit_urine)) {
  print(contrast_coef)
  res <- topTable(vfit_urine, coef = contrast_coef, sort.by="B",
           resort.by = "logFC", p.value = Inf, number = Inf, confint = TRUE)
  
  # put in the same gene order as urineDecideTests
  res <- res[row.names(urineDecideTests),]
  upreg_index = which(urineDecideTests[, contrast_coef] == 1)
  downreg_index = which(urineDecideTests[, contrast_coef] == -1)
  
  good_index <- append(upreg_index, downreg_index)
  # subset res
  res <- res[good_index, ]
  
  write_path <- paste0(fsave_path,
                       'TEST_20231228_', contrast_coef, '_bioivt_urine_deg.csv')
  write.csv(res, file = write_path)
  
  volcanoplot(vfit_urine, coef = contrast_coef, style = 'p-value',
              main = contrast_coef)
  lp <- -log10(vfit_urine$p.value[,contrast_coef])
  ord <- order(lp, decreasing = TRUE)[1:sum(res$adj.P.Val < 0.05)]

  points(vfit_urine$coefficients[ord, contrast_coef], lp[ord], 
         pch = 16, cex = 0.45, col = "#c4d8e2")
}

```

